# Generated by Django 4.0.8 on 2023-01-22 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passions', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='goal_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
