# Generated by Django 4.0.8 on 2023-01-22 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passions', '0003_goal_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='passion',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='passion_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
